name: buchable
version: 1.7.7
summary: Enjoy hearing self-hosted audiobooks.
description: testtesttesttestttest
website: https://github.com/Vito0912/abs_flutter
contact: fito0912@duck.com
source-code: https://github.com/Vito0912/abs_flutter
icon: snap/gui/buchable.png

confinement: strict
base: core22
grade: stable
license: BSD-3-Clause

architectures:
  - build-on: amd64

slots:
  mpris:
    interface: mpris
    name: ABSPlayback

apps:
  buchable:
    command: abs_flutter
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - network
      - network-manager-observe
      - audio-playback
    slots:
      - mpris
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/caca:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vdpau:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/mfx

parts:
  buchable:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libmpv-dev