name: buchable
version: 1.7.7
summary: Enjoy hearing self-hosted audiobooks.
description: testtesttesttestttest
website: https://github.com/Vito0912/abs_flutter
contact: fito0912@duck.com
source-code: https://github.com/Vito0912/abs_flutter
icon: snap/gui/buchable.png

confinement: strict
base: core22
grade: stable
license: BSD-3-Clause

architectures:
  - build-on: amd64

slots:
  dbus-buchable:
    interface: dbus
    bus: session
    name: io.github.vito0912.abs_flutter

apps:
  buchable:
    command: abs_flutter
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - network
      - audio-playback
      - password-manager-service
    slots:
      - dbus-buchable
parts:
  buchable:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0